### ISSUE TITLE
Error 404 Bad Request

### ISSUE THREAD

**Issue by thenewgessiko** [shipgirlproject/Shoukaku#196] opened 2024-08-31 15:35 UTC
In the console, at every playback request I find myself via youtube, spotify, and soundcloud it gives me bad request error 400 why?
![20240830_181328](https://github.com/user-attachments/assets/63bd42b9-5e9a-4539-9457-3aa7df02d6c5)

**Comment by Deivu** [comment] 2024-08-31 15:50
Duplicate of #195

**Closed by Deivu** 2024-08-31 15:50 UTC
